#!/bin/bash
#________________________________________________________________
#░██╗░░░░░░░██╗██╗██╗░░██╗██╗███╗░░██╗░██████╗░  ░█████╗░░██████╗
#░██║░░██╗░░██║██║██║░██╔╝██║████╗░██║██╔════╝░  ██╔══██╗██╔════╝
#░╚██╗████╗██╔╝██║█████═╝░██║██╔██╗██║██║░░██╗░  ██║░░██║╚█████╗░
#░░████╔═████║░██║██╔═██╗░██║██║╚████║██║░░╚██╗  ██║░░██║░╚═══██╗
#░░╚██╔╝░╚██╔╝░██║██║░╚██╗██║██║░╚███║╚██████╔╝  ╚█████╔╝██████╔╝
#░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝╚═╝░░╚══╝░╚═════╝░  ░╚════╝░╚═════╝░
#________________________________________________________________

# Functions

function confirm() {
    read -p "$1? [Y|y|n] " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
}

ubuntuppa() {
    sudo add-apt-repository ppa:aslatter/ppa -y
}

install() {
    sudo apt install $1 -y
}

remove() {
    sudo apt-get remove --auto-remove $1 -y
}

purge() {
    sudo apt-get remove --auto-remove --purge $1 -y
}

# Script


echo "░██╗░░░░░░░██╗██╗██╗░░██╗██╗███╗░░██╗░██████╗░  ░█████╗░░██████╗
░██║░░██╗░░██║██║██║░██╔╝██║████╗░██║██╔════╝░  ██╔══██╗██╔════╝
░╚██╗████╗██╔╝██║█████═╝░██║██╔██╗██║██║░░██╗░  ██║░░██║╚█████╗░
░░████╔═████║░██║██╔═██╗░██║██║╚████║██║░░╚██╗  ██║░░██║░╚═══██╗
░░╚██╔╝░╚██╔╝░██║██║░╚██╗██║██║░╚███║╚██████╔╝  ╚█████╔╝██████╔╝
░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝╚═╝░░╚══╝░╚═════╝░  ░╚════╝░╚═════╝░"

echo "-------------------------------"
echo "---     Checking Distro     ---"
echo "-------------------------------"

DISTRO=$(lsb_release -i | cut -d: -f2 | sed s/'^\t'//)
VERSION=$(lsb_release -r | cut -d: -f2 | sed s/'^\t'//)
CODENAME=$(lsb_release -c | cut -d: -f2 | sed s/'^\t'//)

echo "Distro:" $DISTRO
echo "Version:" $VERSION
echo "Codename:" $CODENAME

echo "------------------------------"
echo "---    Update & Upgrade    ---"
echo "------------------------------"

sudo apt update && sudo apt upgrade -y && sudo apt autoremove

echo "------------------------------"
echo "---       Adding PPA       ---"
echo "------------------------------"

echo "aslatter/ppa"

confirm "Want to continue"

if [ "$DISTRO" = "Pop" ]; then
    if [ "$VERSION" > "21.04"]; then
        echo "Not need"
    else
        ubuntuppa
    fi
elif [ "$DISTRO" = "Ubuntu" ]; then
    ubuntuppa
elif [ "$DISTRO" = "Debian" ]; then
    echo "Debian"
fi

echo "------------------------------"
echo "---      Installation      ---"
echo "------------------------------"

PACKAGES="alacritty xinit awesome"

echo $PACKAGES

confirm "Want to continue"

install $PACKAGES

echo "------------------------------"
echo "---     Removing Gnome     ---"
echo "------------------------------"

GNOME_PACKAGES="ubuntu-gnome-desktop gnome-shell"

purge $GNOME_PACKAGES

sudo apt autoremove

echo "-------------------------------"
echo "---         Configs         ---"
echo "-------------------------------"

echo "Cloning dotfiles"

git clone https://github.com/theredwiking/dotfiles ~/dotfiles

ls -la ~/dotfiles
